// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIAnFuSHcq0lunRSy9GSN5uxDvqX55UF4',
    appId: '1:964047896105:web:a802bdde2225730bf26638',
    messagingSenderId: '964047896105',
    projectId: 'hey-auto-b4378',
    authDomain: 'hey-auto-b4378.firebaseapp.com',
    databaseURL: 'https://hey-auto-b4378-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hey-auto-b4378.appspot.com',
    measurementId: 'G-1M0QNDEGVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWKlFe6vTDXgEuYLIt99C_OBCmsiPhIM8',
    appId: '1:964047896105:android:dedbe7a2ff829b87f26638',
    messagingSenderId: '964047896105',
    projectId: 'hey-auto-b4378',
    databaseURL: 'https://hey-auto-b4378-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hey-auto-b4378.appspot.com',
  );
}
